### ISSUE TITLE
프로젝트 주제 생각해보기.

### ISSUE THREAD

**Issue by KimHuiEun** [KimHuiEun/E-BookSystem#1]
Web Api 기반으로 진행할 주제에 대한 의견 부탁드립니다

c#(EF)
mySQL
winForm
Devexpress
web Api

**Comment by KimHuiEun** [comment]
수강신청관리시스템 - 학번으로 수강신청을 하면 관리자가 학번이랑 수강으로 관리하기.

**Comment by jangsuk701** [comment]
대형마트 판매품목(특정 상품군) 관리, 전시회 관리 프로그램

**Comment by daheenyang** [comment]
비대면으로 지하철 사물함을 기반으로한 도서 대여/반납 프로그램 제안합니다

**Comment by bark-ch** [comment]
도서 대여 반납 프로그램 좋습니다.
