### ISSUE TITLE
오류1. 메인폼에서 작성된 데브 버전 충돌

### ISSUE THREAD

**Issue by KimHuiEun** [KimHuiEun/E-BookSystem#10]
Devexpress v20.02.03 으로 통일

v20.02.04는 최신버전으로 삭제 부탁합니다.

Devexpress 컨트롤 사용 중 버전 동기화가 되지않아 패치 후 풀, 푸시 할 때 참조 관련하여 오류발생.(새로 복제할 때 마다 수동으로 Devexpress를 참조해줘야했음.)

**Comment by bark-ch** [comment]
네 확인하였습니다.

**Comment by daheenyang** [comment]
네 확인했습니다. 기존 버전 삭제하고 dev express 20.02.03으로 재설치, 구동됨 확인하였습니다.

**Comment by jangsuk701** [comment]
네 확인했습니다!
