### ISSUE TITLE
12월 16일 RentSummary 클래스 생성

### ISSUE THREAD

**Issue by jangsuk701** [KimHuiEun/E-BookSystem#21]
차트에 데이터소스를 넣기위해 x,y,z축에 속성값을 생성.
RentSummary 클래스를 추가.  (매개변수 Decade, Count, Genre)

**Comment by daheenyang** [comment]
RentSummary에 테이블이 존재하지 않는 요소를 종합하여 데이터를 추출하여 차트에 적용·사용하기 위해 query 문을 사용한 익명개체를 생성하여 메소드 구현.  dictionary를 사용하여 같은 원리를 적용하여 구현해보기도 함. 궁극적으로 사용은 익명개체를 생성하여 사용하는 방법을 선택함.

**Comment by KimHuiEun** [comment]
RentSummary  클래스 -> Summary 클래스로 변경
