### ISSUE TITLE
12월 17일 클래스 구현

### ISSUE THREAD

**Issue by KimHuiEun** [KimHuiEun/E-BookSystem#22]
클래스 구현

**Comment by KimHuiEun** [comment]
책마다의 대여량 계산 클래스 추가.
방법 : Rent 테이블에서 BookId를 추출하여 리스트화 시키고 카운트를 써서 대여량을 계산.

**Comment by KimHuiEun** [comment]
클래스 명명 정리 필요!

**Comment by daheenyang** [comment]
> 책마다의 대여량 계산 클래스 추가.
> 방법 : Rent 테이블에서 BookId를 추출하여 리스트화 시키고 카운트를 써서 대여량을 계산.

1. 성별-연령-대여량 summary 작성 시, 앞서 사용했던 익명개체 생성 방법이 아닌 dictionary 사용하여 클래스 구현 
2. SQL에서 query문의 where조건 birthyear.year=year로 추출 되지 않을 수 있어서 birthdate의 first date, last date를 사용하여 year을 추출하는 방식으로 변경 사용함.
